---
title: "Team Dynamics and Productivity in Health Care: Evidence from the Military Health System"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Teamwork is a vital component to many organizations’ production function. Likewise turnover occurs for multitude of reasons potentially improving employer-employee match but also disrupting team dynamics. For instance, if teams have task allocated based on each individual member’s comparative advantage, a change in team membership may require finding a new equilibrium. In this paper we estimate the effect of turnover on team productivity while providing additional analysis on how individual team member skill affects overall team productivity. While previous attempts at causal identification on the subject have been hampered by the endogeneity of the turnover decision, we have a novel data source that provides some exogeneity to this decision. We use a 9 year panel of data from the Military Health System (MHS). Distinct from the VA, The MHS is a network of 55 hospitals and nearly 400 clinics providing health care for more than 4 million Tricare Prime insurance beneficiaries.  These beneficiaries include active duty military and their families, as well as military retirees and their families. In the military setting, there are a mix of uniformed service and civilian practitioners. Active duty providers are required to move from one base to another approximately once every two to three years while civilians generally remain in a location. Importantly, the military services’ human resources departments decide where to move these military providers who by law cannot refuse a move. Initial analysis shows that these moves are uncorrelated with provider skill and that the modal team stays together for about a year before either a new provider enters the team or a provider leaves the team. 

  We conduct our analysis using obstetrics and gynecology (OB/GYN) departments, focusing on pregnancies and births. OB/GYN is an ideal setting for several reasons. First, pregnancies are episodic in nature allowing us to analyze total health care production and spending associated with a particular episode of care. Second, pregnancies have very clear outcomes. There is a large literature on pregnancies defining expected levels of outcomes such as Cesarean section rates. Finally OB/GYN providers tend to work together closely. Given the unpredictable nature of births, any provider on the team may deliver the baby, and patients often see multiple members of the team during their prenatal visits.

  Initial analysis shows considerable variation in spending, Cesarean section rates, and readmission rates. For instance, patients at the 90th percentile of average spending per delivery episode cost about 4 times as much as patients at the 10th percentile. For each team disruption a patient endures, physician claims associated with the birth increase by about $300. In addition, these patients are about 10% more likely to deliver via Cesarean section and 10% more likely to have a readmission within 90 days. Interestingly, team tenure has a very low magnitude affect indicating that teams may form quickly but that the disruption is costly.

  Initial results also indicate that there is heterogeneity in how a disruption affects a team. For example, smaller teams tend to be more affected by a disruption than larger teams. We also consider how the heterogeneous effects of individual differences. For example whether the disruption is due gaining an additional provider, losing a provider or both. We also observe compositional differences among the teams. These differences include provider skill type (i.e. nurse practitioner or physician), skill level and seniority. 

  While these results are preliminary, they do have several policy and managerial implications. First, investing in policies and methods to reduce turnover may have a positive impact both in regards to cost and quality of care. Second, as teams seem to form quickly, organizations that anticipate turnover may be better off with a few large disruptions rather than small but consistent disruptions. Finally, these results may impact how health care organizations onboard new employees and allocate tasks during times of disruption.
